### ISSUE TITLE
Replace Cloud Build Maven cache with a .tar file

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-graalvm-support#111]
The Cloud Build Maven cache should be implemented with downloading/extracting/uploading a .tar file instead of using `gsutil`.

See context: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/pull/105#issuecomment-812915381

**Comment by kostacasa** [comment]
Here is a hacky starting point

```yaml
    -   name: 'gcr.io/cloud-builders/gsutil'
        entrypoint: bash
        args:
            - '-c'
            - |
                mkdir -p .m2/repository/
                cd .m2/repository/
                gsutil cp gs://m2_cache/$REPO_NAME.tar .
                if [ -f "$REPO_NAME.tar" ]; then
                    echo "Extracting archive"
                    tar -xf $REPO_NAME.tar
                    echo "Extracted"
                    rm $REPO_NAME.tar
                    ls
                fi
                true
```

```yaml
    # Store m2 cache
    -   name: 'gcr.io/cloud-builders/gsutil'
        entrypoint: bash
        args:
            - '-c'
            - |
                echo "Creating m2 repository tarball..."
                tar --directory /workspace/.m2/repository -cf $REPO_NAME.tar .
                gsutil cp $REPO_NAME.tar gs://m2_cache/
```

This approach completes the transfer in a few seconds usually and tar-ing is very fast.
